[build-system]
requires = ["hatchling>=1.31"]
build-backend = "hatchling.build"

[project]
name = "rangemap-tayra"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.13"
license = "AGPL-3.0-or-later"
keywords = []
authors = [
  { name = "Tayra Sakurai", email = "tayra_sakurai@icloud.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Framework :: Hatch",
  "Intended Audience :: Education",
  "Intended Audience :: End Users/Desktop",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Scientific/Engineering :: GIS",
]
dependencies = [
  "requests>=2.34",
  "folium>=0.20.0",
]

[project.optional-dependencies]
dev = [
  "Sphinx>=9.1",
  "pydata-sphinx-theme>=0.21",
  "numpydoc>=1.11",
  "pytest>=9.1",
]

[project.urls]
Documentation = "https://github.com/Tayra-Sakurai/rangemap-tayra#readme"
Issues = "https://github.com/Tayra-Sakurai/rangemap-tayra/issues"
Source = "https://github.com/Tayra-Sakurai/rangemap-tayra"

[tool.hatch.version]
path = "src/rangemap_tayra/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/rangemap_tayra tests}"

[tool.coverage.run]
source_pkgs = ["rangemap_tayra", "tests"]
branch = true
parallel = true
omit = [
  "src/rangemap_tayra/__about__.py",
]

[tool.hatch.envs.test]
dependencies = [
  "pytest>=9.1",
]
[tool.hatch.envs.dev]
extra-dependencies = [
  "Sphinx>=9.1",
  "pydata-sphinx-theme>=0.21",
  "numpydoc>=1.11",
  "pytest>=9.1",
]

[tool.coverage.paths]
rangemap_tayra = ["src/rangemap_tayra", "*/rangemap-tayra/src/rangemap_tayra"]
tests = ["tests", "*/rangemap-tayra/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
